modules/admin/controllers/MemberController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\EventAttendance;
use app\models\MembershipActivity;
use app\models\Officer;
use app\models\User;
use app\models\UserMembership;
use app\models\MembershipPayment;
use app\modules\admin\models\MembershipActivityForm;
use app\modules\admin\models\MemberSearch;
use app\modules\admin\models\OfficerSearch;
use app\modules\admin\models\MembershipActivitySearch;
use app\modules\admin\models\MembershipPaymentSearch;
use app\modules\admin\models\MemberEventAttendanceSearch;
use app\models\enums\EventType;
use app\models\enums\MembershipType;
use app\models\enums\MemberDiscountType;
use yii\base\Model;
use yii\bootstrap4\Html;
use yii\data\ArrayDataProvider;
use yii\db\Expression;
use yii\db\Query;
use yii\helpers\ArrayHelper;
use yii\web\BadRequestHttpException;
use yii\web\Response;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii2tech\csvgrid\CsvGrid;

/**
 * MemberController implements the CRUD actions for User model.
 */
class MemberController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                        'run-query' => ['POST'],
                        'download-event-attendances' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all User models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = Yii::createObject(MemberSearch::class);
        $dataProvider = $searchModel->search($this->request->queryParams);

        if ($this->request->isPost) {
            $models = $dataProvider->getModels();
            $batchAction = $this->request->post('batch_action');
            $selection = $this->request->post('selection');
            $affectedRows = 0;
            if (Model::loadMultiple($models, $this->request->post()) && Model::validateMultiple($models)) {
                $session = Yii::$app->session;
                switch ($batchAction) {
                    case 'delete':
                        $affectedRows = 0;
                        if (is_array($selection) && count($selection)) {
                            $users = User::find()->where(['in', 'id', $selection]);
                            foreach ($users->each(10) as $user) {
                                $user->delete();
                                $affectedRows++;
                            }

                            $session->setFlash('info', Yii::t('app', '{count,plural,=0{No member has been deleted.} =1{Deleted one member.} other{Deleted # members.}}', ['count' => $affectedRows]));
                        } else {
                            $session->setFlash('warning', Yii::t('app', 'No member has been deleted.'));
                        }
                        break;
                    case 'update':
                        $affectedRows = 0;
                        if (isset($_POST['members-form'])) {
                            if (isset($_POST['members-form']['membership_type']) && ! empty($_POST['members-form']['membership_type'])) {
                                $affectedRows = UserMembership::batchUpdateMembershipType($selection, $_POST['members-form']['membership_type']);
                            } else {
                                foreach ($models as $model) {
                                    if (isset($_POST['User'][$model->id])) {
                                        $membership_type = $model->membership_type;
                                        $year_initial_joined = $model->year_initial_joined;

                                        if (isset($_POST['User'][$model->id]['membership_type'])) {
                                            $membership_type = $_POST['User'][$model->id]['membership_type'];
                                        }

                                        if (isset($_POST['User'][$model->id]['year_initial_joined'])) {
                                            $year_initial_joined = $_POST['User'][$model->id]['year_initial_joined'];
                                        }

                                        $status = $model->status;
                                        if (isset($_POST['User'][$model->id]['status'])) {
                                            $status = $_POST['User'][$model->id]['status'];
                                        }

                                        $membership = $model->userMembership;
                                        $membership->scenario = UserMembership::SCENARIO_UPDATE;
                                        $membership->type = $membership_type;
                                        $membership->year_initial_joined = $year_initial_joined;
                                        $model->status = $status;
                                        if (($model->update() > 0) || ($membership->update() > 0)) {
                                            $affectedRows++;
                                        }
                                    }
                                }
                            }
                        }

                        $session->setFlash('info', Yii::t('app', '{count,plural,=0{No member has been updated.} =1{Updated one member.} other{Updated # members.}}', ['count' => $affectedRows]));
                        break;
                    case 'toggle_lock':
                        $affectedRows = 0;
                        $status = '';
                        $email = '';

                        if (isset($_POST['lock_name_on_certificate_id'])) {
                            $lock_name_on_certificate_id = $_POST['lock_name_on_certificate_id'];
                            if (isset($_POST['User'][$lock_name_on_certificate_id]) && isset($models[$lock_name_on_certificate_id])) {
                                $lock_name_on_certificate = $_POST['User'][$lock_name_on_certificate_id]['lock_name_on_certificate'];
                                $status = $lock_name_on_certificate ? 'locked' : 'unlocked';
                                $model = $models[$lock_name_on_certificate_id];
                                if ($model->update() > 0) {
                                    $email = $model->email;
                                    $affectedRows++;
                                }
                            }
                        }

                        if ($affectedRows) {
                            $session->setFlash('success', Yii::t(
                                'app',
                                'You have {status} the changing of {attribute} of {email}.',
                                [
                                    'status' => Html::tag('strong', $status),
                                    'attribute' => Html::tag('code', 'name_on_certificate'),
                                    'email' => Html::encode($email),
                                ]
                            ));
                        }
                        break;
                    case 'toggle_status':
                        $affectedRows = 0;
                        $status = '';
                        $email = '';

                        if (isset($_POST['status_id'])) {
                            $status_id = $_POST['status_id'];
                            if (isset($_POST['User'][$status_id]) && isset($models[$status_id])) {
                                $status = $_POST['User'][$status_id]['status'];

                                if (! in_array($status, [
                                    User::STATUS_INACTIVE,
                                    User::STATUS_FOR_APPROVAL,
                                ])) {
                                    $session->setFlash('danger', 'The status is invalid.');
                                    break;
                                }

                                $model = $models[$status_id];
                                if ($model->update() > 0) {
                                    $email = $model->email;
                                    $affectedRows++;

                                    if ($model->is_inactive) {
                                        $model->sendEmail();
                                    }
                                }
                            }
                        }

                        if ($affectedRows) {
                            $session->setFlash('success', Yii::t(
                                'app',
                                'An email has been sent to {email} containing instructions on activating the account.',
                                [
                                    'email' => Html::encode($email),
                                ]
                            ));
                        }

                        break;
                    case 'change_membership_type':
                        $affectedRows = 0;
                        $email = '';
                        if (isset($_POST['membership_type_id'])) {
                            $membership_type_id = $_POST['membership_type_id'];
                            if (isset($_POST['User'][$membership_type_id]) && isset($models[$membership_type_id])) {
                                $membership_type = $_POST['User'][$membership_type_id]['membership_type'];
                                $membership_year_initial_joined = isset($_POST['User'][$membership_type_id]['year_initial_joined']) ?
                                    $_POST['User'][$membership_type_id]['year_initial_joined'] : null;
                                $model = $models[$membership_type_id];

modules/admin/controllers/OfficerController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\Officer;
use app\models\UserProfile;
use app\modules\admin\models\OfficerSearch;
use yii\base\Model;
use yii\db\Expression;
use yii\db\Query;
use yii\web\Response;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * OfficerController implements the CRUD actions for Officer model.
 */
class OfficerController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * List members
     *
     * @param string|null $q
     * @param string|null $id
     * 
     * @return Response
     */
    public function actionMemberList($q = null, $id = null)
    {
        $this->response->format = Response::FORMAT_JSON;
        $out = ['results' => ['id' => '', 'text' => '']];
        if (! is_null($q)) {
            $query = (new Query())
                ->select(['id' => '[[user_id]]', 'text' => (new Expression('CONCAT([[first_name]], " ", [[last_name]])'))])
                ->from('{{%user_profile}}')
                ->where(['or', ['like', '[[first_name]]', $q], ['like', '[[last_name]]', $q]])
                ->limit(20);
            $command = $query->createCommand();
            $data = $command->queryAll();
            $out['results'] = array_values($data);
        } else if ($id > 0) {
            $out['results'] = ['id' => $id, 'text' => UserProfile::findOne(['user_id' => $id])->complete_name];
        }

        $this->response->data = $out;

        $this->response->send();
        Yii::$app->end();
    }

    /**
     * Creates a new Officer model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = Yii::createObject(Officer::class);

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['member/officer']);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
            'yearServedRange' => Officer::getYearServedRange(),
        ]);
    }

    /**
     * Deletes an existing Officer model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['member/officer']);
    }

    /**
     * Finds the Officer model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Officer the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Officer::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

modules/admin/views/member/_education.php
<?php

use yii\bootstrap4\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\UserEducation */
?>
<div class="row justify-content-start">
    <div class="col-md-12">
        <?= Html::tag(
            'h3',
            Yii::t('app', '{icon} Education', [
                'icon' => Html::tag(
                    'svg',
                    Html::tag('use', '', ['xlink:href' => Url::to('@web/vendor/@coreui/icons/sprites/free.svg#cil-education')]),
                    ['class' => 'mr-2 c-icon c-icon-xl']
                ),
            ]),
            ['class' => 'mt-2 mb-4 text-dark']
        ) ?>
        <?php if ($model): ?>
            <?= DetailView::widget([
                'model' => $model,
                'options' => ['class' => 'table table-bordered detail-view mb-0'],
                'attributes' => [
                    'institution:veterinaryinstitution',
                    'year_graduated',
                ],
            ]) ?>
        <?php else: ?>
            <p><?= Yii::$app->formatter->memberNoRecords ?></p>
        <?php endif; ?>
    </div>
</div>

modules/admin/views/member/_employment.php
<?php

use yii\bootstrap4\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\UserEmployment */
?>
<div class="row justify-content-start">
    <div class="col-md-12">
        <?= Html::tag(
            'h3',
            Yii::t('app', '{icon} Employment', [
                'icon' => Html::tag(
                    'svg',
                    Html::tag('use', '', ['xlink:href' => Url::to('@web/vendor/@coreui/icons/sprites/free.svg#cil-briefcase')]),
                    ['class' => 'mr-2 c-icon c-icon-xl']
                ),
            ]),
            ['class' => 'mt-2 mb-4 text-dark']
        ) ?>
        <?php if ($model): ?>
            <?= DetailView::widget([
                'model' => $model,
                'options' => ['class' => 'table table-bordered detail-view mb-0'],
                'attributes' => [
                    'company_name',
                    'position',
                    'address:ntext',
                    'subdivision',
                    'barangay',
                    'municipality',
                    'province',
                    'zipcode',
                    'country',
                    'phone_number',
                ],
            ]) ?>
        <?php else: ?>
            <p><?= Yii::$app->formatter->memberNoRecords ?></p>
        <?php endif; ?>
    </div>
</div>

modules/admin/views/member/_event-attendance.php
<?php

use yii\bootstrap4\Html;
use yii\helpers\Url;
use yii\widgets\Pjax;
use kartik\grid\GridView;
use kartik\form\ActiveForm;
use kartik\builder\Form;

/* @var $this yii\web\View */
/* @var $member app\models\User */
/* @var $searchModel app\modules\admin\models\MemberEventAttendanceSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
?>
<div class="card mt-4">
    <div class="card-body">
        <div class="d-flex justify-content-start">
            <?php $form = ActiveForm::begin(['action' => ['download-event-attendances', 'id' => $member->id]]); ?>
                <div class="form-group mb-0">
                    <?= Html::submitButton(Yii::t('app', 'Download CSV'), [
                        'name' => 'batch_action',
                        'value' => 'download-csv',
                        'class' => 'btn btn-success px-4',
                    ]) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
        <?php Pjax::begin(); ?>
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'options' => ['class' => 'mt-4'],
                'tableOptions' => ['class' => 'table-responsive-sm'],
                'headerRowOptions' => ['class' => 'thead-light'],
                'hover' => true,
                'striped' => false,
                'columns' => [
                    [
                        'class' => 'kartik\grid\SerialColumn',
                        'mergeHeader' => false,
                    ],

                    [
                        'attribute' => 'type',
                        'format' => 'eventtype',
                        'value' => function ($model, $key, $index, $column) {
                            return $model->event->type;
                        },
                    ],
                    [
                        'attribute' => 'title',
                        'format' => 'ntext',
                        'value' => function ($model, $key, $index, $column) {
                            return $model->event->title;
                        },
                    ],
                    [
                        'hAlign' => 'center',
                        'attribute' => 'start_date',
                        'format' => 'date',
                        'value' => function ($model, $key, $index, $column) {
                            return $model->event->start_date;
                        },
                    ],
                    [
                        'hAlign' => 'center',
                        'attribute' => 'end_date',
                        'format' => 'date',
                        'value' => function ($model, $key, $index, $column) {
                            return $model->event->end_date;
                        },
                    ],
                    [
                        'hAlign' => 'right',
                        'attribute' => 'cpd_point_earned',
                        'value' => 'cpd_point_earned',
                        'label' => Yii::t('app', 'CPD Point/s Earned'),
                        'format' => ['decimal', 2],
                    ],
                    [
                        'attribute' => 'attended',
                        'format' => 'boolean',
                    ],
                ],
            ]); ?>
        <?php Pjax::end(); ?>
    </div>
</div>

modules/admin/views/member/_membership-activity-details.php
<?php

use yii\bootstrap4\Html;

/* @var $this yii\web\View */
/* @var $model app\models\MembershipActivity */
$formatter = Yii::$app->formatter;
?>
<div class="row justify-content-start">
    <div class="col-2">
        <div class="card mb-0">
            <div class="card-body bg-warning text-white">
                <h4 class="d-flex align-items-center mb-0">
                    <?= Html::encode($model->event_attendance_count) ?>
                    <small class="ml-2"><?= Yii::t('app', 'TOTAL') ?></small>
                </h4>
                <span><?= $formatter->asMembershipType($model->membership_type) ?></span>
            </div>
        </div>
    </div>
    <div class="col-5">
        <div class="card mb-0">
            <div class="card-body bg-light">
                <?php $arr = $model->year_event_attended; ?>
                <?= Yii::t('app', '{count,plural,=0{Event attended with confirmed attendance:} =1{Event attended with confirmed attendance:} other{Events attended with confirmed attendances:}}', ['count' => is_null($arr) ? 0 : count($arr)]) ?>
                <?= Html::tag('br') ?>
                <?php
                if (is_array($arr) && count($arr)) {
                    echo '<span class="badge badge-success">' . implode('</span><span class="badge badge-success ml-1">', $arr) . '</span>';
                } else {
                    echo $formatter->nullDisplay;
                }
                ?>
            </div>
        </div>
    </div>
    <div class="col-5">
        <div class="card mb-0">
            <div class="card-body bg-light">
            <?php $arr = $model->event_attended_year_paid; ?>
                <?= Yii::t('app', '{count,plural,=0{Event attended with confirmed payment:} =1{Event attended with confirmed payment:} other{Events attended with confirmed payments:}}', ['count' => is_null($arr) ? 0 : count($arr)]) ?>
                <?= Html::tag('br') ?>
                <?php
                if (is_array($arr) && count($arr)) {
                    echo '<span class="badge badge-success">' . implode('</span><span class="badge badge-success ml-1">', $arr) . '</span>';
                } else {
                    echo $formatter->nullDisplay;
                }
                ?>
            </div>
        </div>
    </div>
</div>

modules/admin/views/member/_officer.php
<?php

use yii\bootstrap4\Html;
use yii\helpers\Url;
use kartik\form\ActiveForm;
use kartik\builder\TabularForm;
use app\models\Officer;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\admin\models\OfficerSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $form kartik\form\ActiveForm */
?>
<div class="d-flex justify-content-start my-3">
    <?= Html::a(Yii::t('app', 'Create Officer'), ['officer/create'], ['class' => 'btn btn-success px-4']) ?>
</div>
<div>
    <?= $this->render('_search-officer', ['model' => $searchModel]); ?>
</div>
<?php $form = ActiveForm::begin(); ?>
    <?= TabularForm::widget([
        'dataProvider' => $dataProvider,
        'form' => $form,
        'gridSettings' => [
            'tableOptions' => ['class' => 'table-responsive-sm'],
            'headerRowOptions' => ['class' => 'thead-light'],
            'hover' => true,
            'striped' => false,
        ],
        'actionColumn' => [
            'viewOptions' => ['style' => 'display:none'],
            'updateOptions' => ['style' => 'display:none'],
            'width' => '40px',
            'urlCreator' => function ($action, Officer $model, $key, $index, $column) {
                return Url::toRoute(["officer/{$action}", 'id' => $model->id]);
            },
        ],
        'attributes' => [
            'id' => [
                'type' => TabularForm::INPUT_HIDDEN, 
                'columnOptions' => ['hidden' => true],
            ], 
            'complete_name' => [
                'type' => TabularForm::INPUT_STATIC,
                'columnOptions' => ['width' => '30%'],
            ],
            'was_president' => [
                'type' => TabularForm::INPUT_WIDGET,
                'columnOptions' => ['width' => '10%'],
                'widgetClass' => 'kartik\widgets\SwitchInput',
                'options' => [
                    'pluginOptions' => [
                        'onText' => Yii::t('app', 'Yes'),
                        'offText' => Yii::t('app', 'No'),
                        'onColor' => 'success',
                        'offColor' => 'danger',
                    ],
                ],
            ],
            'number_years_served' => [
                'type' => TabularForm::INPUT_STATIC,
                'columnOptions' => ['width' => '10%'],
            ],
            'year_served' => [
                'type' => TabularForm::INPUT_WIDGET,
                'columnOptions' => ['width' => '50%'],
                'widgetClass' => 'kartik\select2\Select2',
                'options' => [
                    'data' => $yearServedRange,
                    'options' => [
                        'multiple' => true,
                    ],
                    'pluginOptions' => [
                        'allowClear' => true,
                    ],
                ],
            ],
        ],
    ]) ?>
    <div class="form-group d-flex justify-content-end">
        <div>
            <?= Html::submitButton(Yii::t('app', 'Batch Delete'), [
                'name' => 'batch_action',
                'value' => 'delete',
                'class' => 'btn btn-danger px-4',
                'data' => ['confirm' => Yii::t('app', 'Are you sure to delete selected item/s?')],
            ]) ?>
            <?= Html::submitButton(Yii::t('app', 'Batch Update'), [
                'name' => 'batch_action',
                'value' => 'update',
                'class' => 'btn btn-primary px-4',
            ]) ?>
        </div>
    </div>
<?php ActiveForm::end(); ?>

modules/admin/views/member/_profile.php
<?php

use yii\bootstrap4\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\UserProfile */
?>
<div class="row justify-content-start">
    <div class="col-md-12">
        <?= Html::tag(
            'h3',
            Yii::t('app', '{icon} Profile', [
                'icon' => Html::tag(
                    'svg',
                    Html::tag('use', '', ['xlink:href' => Url::to('@web/vendor/@coreui/icons/sprites/free.svg#cil-user')]),
                    ['class' => 'mr-2 c-icon c-icon-xl']
                ),
            ]),
            ['class' => 'mt-2 mb-4 text-dark']
        ) ?>
        <?php if ($model): ?>
            <?= DetailView::widget([
                'model' => $model,
                'options' => ['class' => 'table table-bordered detail-view mb-0'],
                'attributes' => [
                    'first_name',
                    'middle_name',
                    'last_name',
                    'suffix',
                    'nickname',
                    'name_on_certificate',
                    'address:ntext',
                    'subdivision',
                    'barangay',
                    'municipality',
                    'province',
                    'zipcode',
                    'country',
                    'phone_number',
                    'mobile_number',
                    'birth_date:date',
                ],
            ]) ?>
        <?php else: ?>
            <p><?= Yii::$app->formatter->memberNoRecords ?></p>
        <?php endif; ?>
    </div>
</div>

modules/admin/views/member/_search-membership-activity.php
<?php

use yii\bootstrap4\Html;
use yii\web\View;
use kartik\form\ActiveForm;
use kartik\builder\Form;
use app\models\enums\MembershipType;

/* @var $this yii\web\View */
/* @var $model app\models\MembershipActivitySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="membership-activity-search">
    <div class="card">
        <div class="card-body bg-light">
            <?php $form = ActiveForm::begin([
                'action' => ['membership-activity'],
                'method' => 'get',
            ]); ?>
                <?= Form::widget([
                    'model' => $model,
                    'form' => $form,
                    'columns' => 2,
                    'attributes' => [
                        'complete_name' => [
                            'type' => Form::INPUT_TEXT,
                            'label' => false,
                            'options' => ['placeholder' => $model->getAttributeLabel('complete_name')],
                        ],
                        'membership_type' => [
                            'type' => Form::INPUT_DROPDOWN_LIST,
                            'items' => [
                                MembershipType::LIFETIME => Yii::t('app', 'Lifetime'),
                                MembershipType::REGULAR => Yii::t('app', 'Regular'),
                            ],
                            'label' => false,
                            'options' => ['prompt' => $model->getAttributeLabel('membership_type')],
                        ],
                    ],
                ]) ?>
                <div class="form-group mb-0">
                    <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
                    <?= Html::a(Yii::t('app', 'Reset'), ['membership-activity'], ['class' => 'btn btn-outline-dark btn-reset']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

modules/admin/views/member/_search-membership-payment.php
<?php

use yii\bootstrap4\Html;
use yii\web\View;
use kartik\form\ActiveForm;
use kartik\builder\Form;

/* @var $this yii\web\View */
/* @var $model app\models\MembershipPaymentSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="membership-payment-search">
    <div class="card">
        <div class="card-body bg-light">
            <?php $form = ActiveForm::begin([
                'action' => ['membership-payment'],
                'method' => 'get',
            ]); ?>
                <?= Form::widget([
                    'model' => $model,
                    'form' => $form,
                    'columns' => 3,
                    'attributes' => [
                        'complete_name' => [
                            'type' => Form::INPUT_TEXT,
                            'label' => false,
                            'options' => ['placeholder' => $model->getAttributeLabel('complete_name')],
                        ],
                    ],
                ]) ?>
                <div class="form-group mb-0">
                    <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
                    <?= Html::a(Yii::t('app', 'Reset'), ['membership-payment'], ['class' => 'btn btn-outline-dark']) ?>
                </div>
            <?php ActiveForm::end(); ?>

        </div>
    </div>

</div>

modules/admin/views/member/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = Yii::t('app', 'Create User');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>